{"trial_id": "0000", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units", "default": null, "conditions": [], "min_value": 64, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.001, "conditions": [], "values": [0.001, 0.0001], "ordered": true}}], "values": {"units": 64, "learning_rate": 0.001, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 2, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1184, in fit\n    tmp_logs = self.train_function(iterator)\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py\", line 885, in __call__\n    result = self._call(*args, **kwds)\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py\", line 933, in _call\n    self._initialize(args, kwds, add_initializers_to=initializers)\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py\", line 759, in _initialize\n    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n    graph_function, _ = self._maybe_define_function(args, kwargs)\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py\", line 3463, in _maybe_define_function\n    graph_function = self._create_graph_function(args, kwargs)\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py\", line 3298, in _create_graph_function\n    func_graph_module.func_graph_from_py_func(\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py\", line 1007, in func_graph_from_py_func\n    func_outputs = python_func(*func_args, **func_kwargs)\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py\", line 668, in wrapped_fn\n    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n  File \"/workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py\", line 994, in wrapper\n    raise e.ag_error_metadata.to_exception(e)\nValueError: in user code:\n\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras/engine/training.py:853 train_function  *\n        return step_function(self, iterator)\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras/engine/training.py:842 step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1286 run\n        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2849 call_for_each_replica\n        return self._call_for_each_replica(fn, args, kwargs)\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3632 _call_for_each_replica\n        return fn(*args, **kwargs)\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras/engine/training.py:835 run_step  **\n        outputs = model.train_step(data)\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras/engine/training.py:788 train_step\n        loss = self.compiled_loss(\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras/engine/compile_utils.py:184 __call__\n        self.build(y_pred)\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras/engine/compile_utils.py:133 build\n        self._losses = tf.nest.map_structure(self._get_loss_object, self._losses)\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/util/nest.py:869 map_structure\n        structure[0], [func(*x) for x in entries],\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/tensorflow/python/util/nest.py:869 <listcomp>\n        structure[0], [func(*x) for x in entries],\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras/engine/compile_utils.py:273 _get_loss_object\n        loss = losses_mod.get(loss)\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras/losses.py:2136 get\n        return deserialize(identifier)\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras/losses.py:2091 deserialize\n        return deserialize_keras_object(\n    /workspace/my-fifth-project/.venv/lib/python3.8/site-packages/keras/utils/generic_utils.py:704 deserialize_keras_object\n        raise ValueError(\n\n    ValueError: Unknown loss function: category_crossentropy. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.\n\n"}